apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kubeedge-app: ixpe-video-processor-stage-3
  name: ixpe-video-processor-stage-3
  namespace: default
spec:
  selector:
    matchLabels:
      kubeedge-app: ixpe-video-processor-stage-3
  template:
    metadata:
      labels:
        kubeedge-app: ixpe-video-processor-stage-3
    spec:
      hostNetwork: true
      imagePullSecrets:
      - name: harbor-docker-secret
      containers:
      - name: ixpe-video-processor-stage-3
        image: mykubeedge.com/ixpe/ixpe_stg3
        imagePullPolicy: IfNotPresent
