apiVersion: v1
kind: Service
metadata:
  name: ixpe-video-result
spec:
  selector:
      kubeedge-app: ixpe-video-aggregator
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9854
      nodePort: 30005
