apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-generator-1
  namespace: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-generator-1
  template:
    metadata:
      labels:
        app: video-generator-1
    spec:
      containers:
      - name: video-generator
        image: localhost:5000/gen-env:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: DATA_SOURCE
          value: rtsp://192.168.0.109:8554/mystream
        - name: ID
          value: testapp_video_generator_1
        - name: SOURCE_NAME
          value: video_generator_1
        - name: RABBIT_MQ_QUEUE
          value: testapp/video_generator
        - name: INIT_PRIORITY
          value: "5"
        - name: TUNED_PARAMETERS_INIT
          value: '{"frames_per_task": 5, "skipping_frame_interval": 5}'
        - name: TUNED_PARAMETERS_REDIS_KEY
          value: testapp/video_generator_1/tuned_parameters
        - name: PRIORITY_REDIS_KEY
          value: testapp/video_generator_1/priority

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-aggregator-1
  namespace: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-aggregator-1
  template:
    metadata:
      labels:
        app: video-aggregator-1
    spec:
      containers:
      - name: video-aggregator
        image: localhost:5000/agg-env:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: ID
          value: testapp_video_aggregator_1
        - name: RABBIT_MQ_INCOMING_QUEUE
          value: testapp/video_aggregator_1
        - name: TUNED_PARAMETERS_INIT
          value: '{ "window_size": 8 }'
        - name: FLASK_PORT
          value: "9854"

