apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-stage-1
  namespace: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-processor-stage-1
  template:
    metadata:
      labels:
        app: video-processor-stage-1
    spec:
      containers:
      - name: video-processor-stage-1
        image: localhost:5000/pro-stg1-env:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: ID
          value: testapp_video_processor_stage_1
        - name: RABBIT_MQ_INCOMING_QUEUE
          value: testapp/video_generator
        - name: RABBIT_MQ_OUTGOING_QUEUE
          value: testapp/video_processor_stage_1
        - name: INIT_PRIORITY
          value: 5
        - name: TUNED_PARAMETERS_INIT
          value: { "a": 1, "b": 2, "c": 3}
        - name: TUNED_PARAMETERS_REDIS_KEY
          value: testapp/video_generator_1/tuned_parameters
        - name: PRIORITY_REDIS_KEY
          value: testapp/video_generator_1/priority

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-stage-2
  namespace: testapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-processor-stage-2
  template:
    metadata:
      labels:
        app: video-processor-stage-2
    spec:
      containers:
      - name: video-processor-stage-2
        image: localhost:5000/pro-stg2-env:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: ID
          value: testapp_video_processor_stage_2
        - name: RABBIT_MQ_INCOMING_QUEUE
          value: testapp/video_processor_stage_1
        - name: RABBIT_MQ_OUTGOING_QUEUE
          value: testapp/video_processor_stage_2
        - name: INIT_PRIORITY
          value: 3
        - name: TUNED_PARAMETERS_INIT
          value: { "a": 1, "b": 2, "c": 3}
        - name: TUNED_PARAMETERS_REDIS_KEY
          value: testapp/video_generator_2/tuned_parameters
        - name: PRIORITY_REDIS_KEY
          value: testapp/video_generator_2/priority